ALTER TABLE `form_psychotherapy_note`
    ADD COLUMN IF NOT EXISTS subjective TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS objective TEXT DEFAULT NULL,

    ADD COLUMN IF NOT EXISTS orientation VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS attention VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS appearance VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS behavior VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS speech VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS affect VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS mood VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS thought_process VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS thought_content VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS judgment VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS insight VARCHAR(255) DEFAULT NULL,

    ADD COLUMN IF NOT EXISTS denies_all_risk TINYINT(1) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS suicide_level VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS homicide_level VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS selfharm_level VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS risk_info TEXT DEFAULT NULL
    ADD COLUMN IF NOT EXISTS overall_risk ENUM('None','Low','Moderate','High'),

    ADD COLUMN IF NOT EXISTS clinical_summary TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS diagnostic_support TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS assessment_symptoms ENUM('Escalated','Maintained','Improved'),
    ADD COLUMN IF NOT EXISTS medical_necessity TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS therapeutic_interventions TEXT DEFAULT NULL,

    ADD COLUMN IF NOT EXISTS treatment_goals TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS goals_progress ENUM('Regressed','No change', 'Progressed', 'Goals achieved'),
    ADD COLUMN IF NOT EXISTS barriers TEXT DEFAULT NULL,

    ADD COLUMN IF NOT EXISTS next_steps TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS next_appt_date DATE DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS next_appt_time TIME DEFAULT NULL;
